### ISSUE TITLE
cloudwatch logs to ELK stack

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#184]

**Comment by fauzigo** [comment]
At the moment we are sending logs from cloudwatch to the CSOC account, and from there, we are sending them to ES.

We are not doing individual streaming from CloudWatch to ES per commons account, just for the CSOC account unless this is explicitly requested.

**Comment by fauzigo** [comment]
Currently this is working for commons that are spun up through gen3. 

ElasticSearch is up and waiting for resources to send data over. The description of this issue is kind of vague regarding the scope of what should be sent over to ELK. 

However, so far each common build up creates a Log group, then create a subscription filter to that which ties it up to the CSOC account and firehoses do the rest. 

More information at https://github.com/uc-cdis/cloud-automation/tree/master/tf_files/csoc_common_logging

**Comment by trevars** [comment]
Need work to bring up Kibana dashboard so we can look at the logs.

**Comment by fauzigo** [comment]
After recent updates of fluentd, the logging situation seems like it improved.

keeping this opened until Monday if nothing else comes up.
