### ISSUE TITLE
PXD-410 ⁃ create job to populate test data given a dictionary

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#210]
try Walt's data simulator https://github.com/occ-data/data-simulator
it should generate a bunch of tsvs given a dictionary
dockerize and create a k8s job that can be run to populate test data

**Comment by giangbui** [comment]
10 hours so far but have not finished yet
~ 2 hours to figure out how to run R
~ 2 hours to fix data simulator so that the files are generated in submission orders
~ 4 hours to write the python code to submit testing data by hitting sheepdog endpoint
~ 2 hours to debug the code 

It seems that the testing files from simulator software not generated correctly. Need to talk with Francisco

**Comment by giangbui** [comment]
~ 8 hours. Ready to go

**Comment by trevars** [comment]
There is a bug that needs to be figured out.
