### ISSUE TITLE
PXD-305 ⁃ harvest S3 and ELB log buckets into CSOC Kinesis stream

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#237]
I think this is a good idea, but might be overkill - check with Fauzi.

https://aws.amazon.com/blogs/big-data/build-a-serverless-architecture-to-analyze-amazon-cloudfront-access-logs-using-aws-lambda-amazon-athena-and-amazon-kinesis-analytics/

**Comment by fauzigo** [comment]
Yes, possible, unknown how log would it take though.

If the main idea is to send logs to the CSOC account the, the best way to do it would be putting the logs in cloudwatch first o we can tie everything together. Will be investigating more of possible solutions and/or alternatives to achieve this at convenience.

**Comment by rpowellgit** [comment]
i concur, lets hold off for now on duplicating effort

**Comment by trevars** [comment]
@rpowellgit does someone from BSD ISO need to take care of this or are they waiting on this?

**Comment by trevars** [comment]
Fauzi said it would be relatively easy for him to do .... but he is stretched pretty thin.

**Comment by philloooo** [comment]
➤ Fauzi Gomez commented:

The plan is the following:

S3 Access:

CloudTrail -> S3 ( a different bucket ) and CloudWatchLog > Subscription filter against CSOC's Kinesis stream > Lambda function > Kinesis Firehose > ES and S3 (CSOC obviously). 

This needs to be terraformed.

ELB Access:

Haven't found a way to send ELB access onto CloudWatchLogs, only to an S3 bucket. If there is a way to send whatever is sent to S3, then we'll use said method. Otherwise, we need to find a way to send from S3 to a Kinesis stream on another account ? This remains unknown yet.
